export type Rc6DatasetState =
  | "READY"
  | "RETAINED_REQUIRES_BUILD_CONFIRMATION"
  | "SCHEMA_READY_EMPTY"
  | "HELD";

export type Rc6CacheClass = "CORE_STABLE" | "DEPENDENCY_DRIVEN" | "COMMERCIAL_DYNAMIC";

export type Rc6Snapshot = "core" | "content" | "commercial" | "reference";

export interface Rc6DatasetContract {
  key: string;
  tabName: string;
  state: Rc6DatasetState;
  expectedRows: number;
  primaryKey: string;
  cacheClass: Rc6CacheClass;
  snapshot: Rc6Snapshot;
  publicConsumer: boolean;
  authoritativeEmpty: boolean;
  notes?: string;
}

const dataset = (input: Rc6DatasetContract): Rc6DatasetContract => Object.freeze(input);

export const RC6_RUNTIME_DATASETS = Object.freeze({
  settings: dataset({
    key: "settings",
    tabName: "01_Settings",
    state: "RETAINED_REQUIRES_BUILD_CONFIRMATION",
    expectedRows: 11,
    primaryKey: "Review Status",
    cacheClass: "CORE_STABLE",
    snapshot: "core",
    publicConsumer: false,
    authoritativeEmpty: false,
    notes: "Selective control-field reader only; do not expose the mixed validation table as generic frontend settings.",
  }),
  airlines: dataset({
    key: "airlines",
    tabName: "02_Airlines",
    state: "READY",
    expectedRows: 114,
    primaryKey: "Airline ID",
    cacheClass: "CORE_STABLE",
    snapshot: "core",
    publicConsumer: true,
    authoritativeEmpty: false,
  }),
  airlineRules: dataset({
    key: "airlineRules",
    tabName: "03_Airline Rules",
    state: "READY",
    expectedRows: 425,
    primaryKey: "Rule ID",
    cacheClass: "DEPENDENCY_DRIVEN",
    snapshot: "core",
    publicConsumer: true,
    authoritativeEmpty: false,
  }),
  specialBaggageAll: dataset({
    key: "specialBaggageAll",
    tabName: "04_Special Baggage All",
    state: "RETAINED_REQUIRES_BUILD_CONFIRMATION",
    expectedRows: 24,
    primaryKey: "Item ID",
    cacheClass: "DEPENDENCY_DRIVEN",
    snapshot: "reference",
    publicConsumer: false,
    authoritativeEmpty: false,
    notes: "Reference/source catalogue. User-facing results come from specialBaggageResults.",
  }),
  specialBaggageResults: dataset({
    key: "specialBaggageResults",
    tabName: "04.1_Special Baggage Results",
    state: "READY",
    expectedRows: 21,
    primaryKey: "Result ID",
    cacheClass: "DEPENDENCY_DRIVEN",
    snapshot: "content",
    publicConsumer: true,
    authoritativeEmpty: false,
    notes: "RC6 contract is 21 governed results.",
  }),
  faqs: dataset({
    key: "faqs",
    tabName: "05_FAQs",
    state: "READY",
    expectedRows: 5,
    primaryKey: "FAQ ID",
    cacheClass: "CORE_STABLE",
    snapshot: "content",
    publicConsumer: true,
    authoritativeEmpty: false,
  }),
  tips: dataset({
    key: "tips",
    tabName: "06_Tips",
    state: "READY",
    expectedRows: 182,
    primaryKey: "Tip ID",
    cacheClass: "CORE_STABLE",
    snapshot: "content",
    publicConsumer: true,
    authoritativeEmpty: false,
  }),
  siteContent: dataset({
    key: "siteContent",
    tabName: "07_Site Content",
    state: "READY",
    expectedRows: 12,
    primaryKey: "Content ID",
    cacheClass: "CORE_STABLE",
    snapshot: "content",
    publicConsumer: true,
    authoritativeEmpty: false,
  }),
  navigation: dataset({
    key: "navigation",
    tabName: "07.1_Navigation",
    state: "RETAINED_REQUIRES_BUILD_CONFIRMATION",
    expectedRows: 1,
    primaryKey: "Link ID",
    cacheClass: "CORE_STABLE",
    snapshot: "content",
    publicConsumer: true,
    authoritativeEmpty: false,
    notes: "Inactive rows must remain suppressed even when Publish is truthy.",
  }),
  seoPages: dataset({
    key: "seoPages",
    tabName: "08_SEO Pages",
    state: "RETAINED_REQUIRES_BUILD_CONFIRMATION",
    expectedRows: 15,
    primaryKey: "SEO ID",
    cacheClass: "CORE_STABLE",
    snapshot: "content",
    publicConsumer: true,
    authoritativeEmpty: false,
    notes: "Retained rows are not public merely because they exist; publication gates still apply.",
  }),
  travelNotifications: dataset({
    key: "travelNotifications",
    tabName: "08.1_Travel Notifications",
    state: "SCHEMA_READY_EMPTY",
    expectedRows: 0,
    primaryKey: "Notification ID",
    cacheClass: "DEPENDENCY_DRIVEN",
    snapshot: "content",
    publicConsumer: true,
    authoritativeEmpty: true,
  }),
  articles: dataset({
    key: "articles",
    tabName: "08.2_Articles",
    state: "READY",
    expectedRows: 15,
    primaryKey: "Article ID",
    cacheClass: "CORE_STABLE",
    snapshot: "content",
    publicConsumer: true,
    authoritativeEmpty: false,
  }),
  articleSections: dataset({
    key: "articleSections",
    tabName: "08.2.1_Article_Sections",
    state: "READY",
    expectedRows: 49,
    primaryKey: "Section ID",
    cacheClass: "CORE_STABLE",
    snapshot: "content",
    publicConsumer: true,
    authoritativeEmpty: false,
  }),
  askQuestions: dataset({
    key: "askQuestions",
    tabName: "08.3_Ask_Questions",
    state: "SCHEMA_READY_EMPTY",
    expectedRows: 0,
    primaryKey: "Question ID",
    cacheClass: "DEPENDENCY_DRIVEN",
    snapshot: "content",
    publicConsumer: false,
    authoritativeEmpty: true,
    notes: "Private/test submissions are excluded from public RC6 publication.",
  }),
  askAnswers: dataset({
    key: "askAnswers",
    tabName: "08.3.1_Ask_Answers",
    state: "SCHEMA_READY_EMPTY",
    expectedRows: 0,
    primaryKey: "Answer ID",
    cacheClass: "DEPENDENCY_DRIVEN",
    snapshot: "content",
    publicConsumer: false,
    authoritativeEmpty: true,
  }),
  travelAlerts: dataset({
    key: "travelAlerts",
    tabName: "08.4_Travel_Alerts",
    state: "SCHEMA_READY_EMPTY",
    expectedRows: 0,
    primaryKey: "Alert ID",
    cacheClass: "DEPENDENCY_DRIVEN",
    snapshot: "content",
    publicConsumer: true,
    authoritativeEmpty: true,
  }),
  legacyAffiliatePlacements: dataset({
    key: "legacyAffiliatePlacements",
    tabName: "09_Affiliate_Placements",
    state: "RETAINED_REQUIRES_BUILD_CONFIRMATION",
    expectedRows: 0,
    primaryKey: "Product Name",
    cacheClass: "CORE_STABLE",
    snapshot: "commercial",
    publicConsumer: false,
    authoritativeEmpty: true,
    notes: "Compatibility-only empty dataset. Not RC6 commercial authority.",
  }),
  lab: dataset({
    key: "lab",
    tabName: "10_Lab",
    state: "READY",
    expectedRows: 1,
    primaryKey: "Lab ID",
    cacheClass: "CORE_STABLE",
    snapshot: "content",
    publicConsumer: true,
    authoritativeEmpty: false,
  }),
  labGameCatalogue: dataset({
    key: "labGameCatalogue",
    tabName: "10.1_Lab_Game_Catalogue",
    state: "READY",
    expectedRows: 1,
    primaryKey: "Game ID",
    cacheClass: "CORE_STABLE",
    snapshot: "content",
    publicConsumer: true,
    authoritativeEmpty: false,
    notes: "Only the certified route is eligible; held games remain inactive.",
  }),
  countries: dataset({
    key: "countries",
    tabName: "11_Countries_Base",
    state: "RETAINED_REQUIRES_BUILD_CONFIRMATION",
    expectedRows: 133,
    primaryKey: "Country_ID",
    cacheClass: "CORE_STABLE",
    snapshot: "reference",
    publicConsumer: false,
    authoritativeEmpty: false,
    notes: "Shared reference dataset; not WillItFit route authority.",
  }),
  countryFacts: dataset({
    key: "countryFacts",
    tabName: "11.1_Country_Travel_Facts",
    state: "RETAINED_REQUIRES_BUILD_CONFIRMATION",
    expectedRows: 132,
    primaryKey: "Country_ID",
    cacheClass: "DEPENDENCY_DRIVEN",
    snapshot: "reference",
    publicConsumer: false,
    authoritativeEmpty: false,
    notes: "Dormant shared travel-reference data until an approved WillItFit feature consumes it.",
  }),
  redirects: dataset({
    key: "redirects",
    tabName: "15_Redirects",
    state: "RETAINED_REQUIRES_BUILD_CONFIRMATION",
    expectedRows: 0,
    primaryKey: "Redirect ID",
    cacheClass: "CORE_STABLE",
    snapshot: "core",
    publicConsumer: false,
    authoritativeEmpty: true,
  }),
  productGroups: dataset({
    key: "productGroups",
    tabName: "runtime_product_groups",
    state: "READY",
    expectedRows: 20,
    primaryKey: "productGroupId",
    cacheClass: "CORE_STABLE",
    snapshot: "commercial",
    publicConsumer: true,
    authoritativeEmpty: false,
  }),
  brands: dataset({
    key: "brands",
    tabName: "runtime_brands",
    state: "SCHEMA_READY_EMPTY",
    expectedRows: 0,
    primaryKey: "brandId",
    cacheClass: "CORE_STABLE",
    snapshot: "commercial",
    publicConsumer: true,
    authoritativeEmpty: true,
  }),
  products: dataset({
    key: "products",
    tabName: "runtime_products",
    state: "SCHEMA_READY_EMPTY",
    expectedRows: 0,
    primaryKey: "productId",
    cacheClass: "CORE_STABLE",
    snapshot: "commercial",
    publicConsumer: true,
    authoritativeEmpty: true,
  }),
  productCompatibility: dataset({
    key: "productCompatibility",
    tabName: "runtime_product_compatibility",
    state: "SCHEMA_READY_EMPTY",
    expectedRows: 0,
    primaryKey: "compatibilityId",
    cacheClass: "DEPENDENCY_DRIVEN",
    snapshot: "commercial",
    publicConsumer: true,
    authoritativeEmpty: true,
  }),
  productAssessments: dataset({
    key: "productAssessments",
    tabName: "runtime_product_assessments_summary",
    state: "SCHEMA_READY_EMPTY",
    expectedRows: 0,
    primaryKey: "productId",
    cacheClass: "DEPENDENCY_DRIVEN",
    snapshot: "commercial",
    publicConsumer: true,
    authoritativeEmpty: true,
  }),
  retailers: dataset({
    key: "retailers",
    tabName: "runtime_retailers",
    state: "SCHEMA_READY_EMPTY",
    expectedRows: 0,
    primaryKey: "retailerId",
    cacheClass: "CORE_STABLE",
    snapshot: "commercial",
    publicConsumer: true,
    authoritativeEmpty: true,
  }),
  offers: dataset({
    key: "offers",
    tabName: "runtime_offers",
    state: "SCHEMA_READY_EMPTY",
    expectedRows: 0,
    primaryKey: "offerId",
    cacheClass: "COMMERCIAL_DYNAMIC",
    snapshot: "commercial",
    publicConsumer: true,
    authoritativeEmpty: true,
  }),
  priceIntelligence: dataset({
    key: "priceIntelligence",
    tabName: "runtime_price_intelligence",
    state: "SCHEMA_READY_EMPTY",
    expectedRows: 0,
    primaryKey: "productId",
    cacheClass: "COMMERCIAL_DYNAMIC",
    snapshot: "commercial",
    publicConsumer: true,
    authoritativeEmpty: true,
  }),
  affiliateRoutes: dataset({
    key: "affiliateRoutes",
    tabName: "runtime_affiliate_routes",
    state: "SCHEMA_READY_EMPTY",
    expectedRows: 0,
    primaryKey: "affiliateRouteId",
    cacheClass: "COMMERCIAL_DYNAMIC",
    snapshot: "commercial",
    publicConsumer: true,
    authoritativeEmpty: true,
  }),
  recommendations: dataset({
    key: "recommendations",
    tabName: "runtime_recommendations",
    state: "SCHEMA_READY_EMPTY",
    expectedRows: 0,
    primaryKey: "recommendationId",
    cacheClass: "DEPENDENCY_DRIVEN",
    snapshot: "commercial",
    publicConsumer: true,
    authoritativeEmpty: true,
  }),
  cards: dataset({
    key: "cards",
    tabName: "runtime_cards",
    state: "SCHEMA_READY_EMPTY",
    expectedRows: 0,
    primaryKey: "cardId",
    cacheClass: "CORE_STABLE",
    snapshot: "commercial",
    publicConsumer: true,
    authoritativeEmpty: true,
  }),
  cardPlacements: dataset({
    key: "cardPlacements",
    tabName: "runtime_card_placements",
    state: "SCHEMA_READY_EMPTY",
    expectedRows: 0,
    primaryKey: "placementId",
    cacheClass: "DEPENDENCY_DRIVEN",
    snapshot: "commercial",
    publicConsumer: true,
    authoritativeEmpty: true,
  }),
  pages: dataset({
    key: "pages",
    tabName: "runtime_pages",
    state: "SCHEMA_READY_EMPTY",
    expectedRows: 0,
    primaryKey: "pageId",
    cacheClass: "CORE_STABLE",
    snapshot: "commercial",
    publicConsumer: true,
    authoritativeEmpty: true,
  }),
  pageSections: dataset({
    key: "pageSections",
    tabName: "runtime_page_sections",
    state: "SCHEMA_READY_EMPTY",
    expectedRows: 0,
    primaryKey: "pageSectionId",
    cacheClass: "CORE_STABLE",
    snapshot: "commercial",
    publicConsumer: true,
    authoritativeEmpty: true,
  }),
  methodology: dataset({
    key: "methodology",
    tabName: "runtime_methodology",
    state: "SCHEMA_READY_EMPTY",
    expectedRows: 0,
    primaryKey: "methodId",
    cacheClass: "CORE_STABLE",
    snapshot: "commercial",
    publicConsumer: true,
    authoritativeEmpty: true,
  }),
} satisfies Record<string, Rc6DatasetContract>);

export type Rc6DatasetName = keyof typeof RC6_RUNTIME_DATASETS;

export function getRc6Dataset(name: Rc6DatasetName): Rc6DatasetContract {
  return RC6_RUNTIME_DATASETS[name];
}

export function isAuthoritativeEmptyDataset(name: Rc6DatasetName): boolean {
  return RC6_RUNTIME_DATASETS[name].authoritativeEmpty;
}

export function rc6DatasetsForSnapshot(snapshot: Rc6Snapshot): Rc6DatasetContract[] {
  return Object.values(RC6_RUNTIME_DATASETS).filter((entry) => entry.snapshot === snapshot);
}
